# Generated by Django 4.0.7 on 2022-09-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadTeacher',
            new_name='Principal',
        ),
    ]
