# Generated by Django 4.0.7 on 2022-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_headteacher_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdetails',
            name='Staff_id',
        ),
        migrations.RemoveField(
            model_name='teacherdetails',
            name='image',
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='Students',
            field=models.ManyToManyField(blank=True, null=True, to='users.studentdetails'),
        ),
    ]
