# Generated by Django 4.0.7 on 2022-09-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_teacherdetails_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='Students',
            field=models.ManyToManyField(blank=True, null=True, related_name='%(class)s_students', to='users.student'),
        ),
    ]
